# Generated by Django 4.2.2 on 2023-08-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuvako', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuvako',
            name='Coming',
            field=models.BooleanField(default=False),
        ),
    ]
