# Generated by Django 4.2.2 on 2023-08-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyakarta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyakarta',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='karyakarta',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='karyakarta',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='karyakarta',
            name='LastName',
        ),
    ]
