# Generated by Django 4.2.2 on 2023-08-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyakarta', '0002_remove_karyakarta_area_remove_karyakarta_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyakarta',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='karyakarta',
            old_name='Username',
            new_name='username',
        ),
    ]
