# Generated by Django 4.2.2 on 2023-08-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyakarta', '0004_karyakartalist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyakartalist',
            name='hashed_password',
        ),
    ]
