# Generated by Django 4.2.2 on 2023-08-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyakarta', '0006_delete_karyakartalist_remove_karyakarta_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyakarta',
            name='hashed_password',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='karyakarta',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
